name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build angular app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Npm install and build
        run: |
          npm ci
          npm run build
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-app
          path: |
            dist/
            nginx.conf

  docker:
    runs-on: ubuntu-latest
    environment: CI
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Add PACKAGE_VERSION env property with package version
        run: echo "PACKAGE_VERSION=`cat package.json | grep '"version"' | cut -d'"' -f4`" >> $GITHUB_ENV
      - name: Download built app
        uses: actions/download-artifact@v4
        with:
          name: built-app
      - name: List files
        run: ls -la
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: egozavr/gitlab-search-ui:${{ env.SHORT_SHA }},egozavr/gitlab-search-ui:v${{ env.PACKAGE_VERSION }},egozavr/gitlab-search-ui:latest
